name: Cypress E2E Test
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment

jobs:
    data-prep-train:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: |
                  echo "hello"
    verify-training-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: |
                  echo "hello"
