name: Test

on:
    workflow_dispatch:
        inputs:
            environment:
                required: true
                type: choice
                description: Test Environment
                default: "stage"
                options:
                    - dev
                    - test
                    - stage
            user-flow:
                required: true
                type: choice
                description: User Flow
                options:
                    - Check 1
                    - Check 2
               
env:
    CYPRESS_BASE_URL: https://${{ github.event.inputs.environment }}.com

jobs:
    check-1:
        if: github.event.inputs.user-flow == 'Check 1'
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "CYPRESS_ENV_${{ github.event.inputs.environment }}"
